apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: value
  name: renato-nodejs-template
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
